### ISSUE TITLE
Error in read_binary_radolan_file with new url

### ISSUE THREAD

**Issue by wseis** [KWB-R/kwb.dwd#10]
Hi Hauke,

folgende Fehlermeldung wenn ich neue URL in unsere Funktion eingebe:
Skript auf Basis von letztem Fabian update auf Protonmail

Habe Dateien auf der Ente unter radolan gespeichert:

Aufruf Funktion:
```kwb.dwd::read_binary_radolan_file(r$url)```
Fehlermeldung:
Error in file(path, "rb") : cannot open the connection In addition: Warning message: In file(path, "rb") :   cannot open URL 'https://bvq0pskv98.execute-api.eu-central-1.amazonaws.com/prod?from=20190101&to=20190131&time=2250': HTTP status was '403 Forbidden'

 
  |

**Comment by hsonne** [comment]
Hi, @wseis!

I have written a new function `get_radolan_urls_bucket()` that is now available on the dev branch of fhpredict. It uses the web service created by Fabian and returns the URLs that refer to first and last day and time string requested. You can pass these URLs directly to `kwb.dwd::read_binary_radolan_file()`. 

Try to follow the instructions below (uncomment as required). Does that work?
```
# Install the usethis package if not yet installed
# install.packages("usethis")

# Open the .Renviron file
# usethis::edit_r_environ()
#
# Add the following line (without '#') and replace ... with the actual token
# TOKEN_PROD=...
#
# Save and close .Renviron

# Update our package fhpredict from the dev branch
remotes::install_github("kwb-r/fhpredict@dev", upgrade = "never")

# Restart R (Ctrl + Shift + F10)

# Get and print some URLs
(urls <- fhpredict::get_radolan_urls_bucket(
  from = "20180707", to = "20180708", time = "1050"
))

# Read all binary files from the URLs
raster_rains <- lapply(urls, kwb.dwd::read_binary_radolan_file)

```
