### ISSUE TITLE
kwb.dwd::opendata_files() function missing

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.dwd#11]
In the vignette `radolan.Rmd` the following function is used but not available in the `kwb.dwd` R package

https://github.com/KWB-R/kwb.dwd/blob/f66f1e17e9b7ac9adcc1ce07f756432acab06d4d/vignettes/radolan.Rmd#L59

Thus Travis build fails with the following error message:
```
Error: processing vignette 'radolan.Rmd' failed with diagnostics:
'opendata_files' is not an exported object from 'namespace:kwb.dwd'
```

(https://travis-ci.org/KWB-R/kwb.dwd/jobs/553310111#L2191)

**Comment by hsonne** [comment]
This was corrected in 396476eff894d2b040c19840599a76074ce5f378
