### ISSUE TITLE
Function renaming required

### ISSUE THREAD

**Issue by LukasGue** [KWB-R/kwb.dwd#24]
The functions **calculate_potential_evaporation_stats** and **read_potential_evaporation_from_url** need to be renamed, as they are used for getting precipitation data as well.

https://github.com/KWB-R/kwb.dwd/blob/facaef4988a0de98dc311fae64cf4b20652adfc0/R/load_precipitation_berlin.R#L47
https://github.com/KWB-R/kwb.dwd/blob/facaef4988a0de98dc311fae64cf4b20652adfc0/R/load_precipitation_berlin.R#L49

**Comment by hsonne** [comment]
Done with #27
