### ISSUE TITLE
Renaming of R-script 'load_potential_evaporation_berlin.R'

### ISSUE THREAD

**Issue by LukasGue** [KWB-R/kwb.dwd#32]
Maybe we should rename this file as it contains also a function to load precipitation.

This file only exists in order to use the old functions. Should it remain, or should I rewrite my functions directly as 'load_monthly_variable_for_region(...)' instead of using the 'meta'-functions of this script?

https://github.com/KWB-R/kwb.dwd/blob/4d8ef69b852eeb62d4b65c2ecd402e874f1d3ba4/R/load_potential_evaporation_berlin.R

**Comment by hsonne** [comment]
Indeed. Closed via 0eca569
