### ISSUE TITLE
read_daily_data_over_shape(): allow not only `evapo_p` but also `precipitation`

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.dwd#37]
I am using this function currently (see here: https://github.com/KWB-R/flextreat.hydrus1d/blob/1077d6a7d5515a07ac484e3fb56cdf3a854994a1/data-raw/climate_data.R#L44) in order to derive the `potential evaporation`. 

Would be great if I could also use it for `precipitation` so I dont need to rely on a single monitoring station from R package `rdwd` (see here: https://github.com/KWB-R/flextreat.hydrus1d/blob/1077d6a7d5515a07ac484e3fb56cdf3a854994a1/data-raw/climate_data.R#L13) as `read_daily_over_shape only()` currently only accepts `evapo_p` as input (see: https://github.com/KWB-R/kwb.dwd/blob/935c5c8b698f05898aacdc190ccddd0910bdea9d/R/read_daily_data_over_shape.R#L16)

**Comment by hsonne** [comment]
I extended `read_daily_data_over_shape()` to support all possible variables. The function `list_daily_grids_germany_tgz()` tells you which variables are available: 
```
> kwb.dwd:::list_daily_grids_germany_tgz("x")
 Error in match.arg(variable, c("evapo_p", "evapo_r", "frost_depth", "soil_moist", : 
'arg' should be one of “evapo_p”, “evapo_r”, “frost_depth”, “soil_moist”, “soil_temperature_5cm”
```
Unfortunately, precipitation data are not available on a daily basis.

I added a function [`read_monthly_data_over_shape()`](https://github.com/KWB-R/kwb.dwd/commit/f07f65a3f302dfd43cb570227c83ae3464edc6b9) that can provide precipitation data as well as further variables. The function `list_monthly_grids_germany_asc_gz()` informs about possible variables:
```
> kwb.dwd:::list_monthly_grids_germany_asc_gz(variable = "x")
 Error in match.arg(variable, c("air_temperature_max", "air_temperature_mean", : 
'arg' should be one of “air_temperature_max”, “air_temperature_mean”, “air_temperature_min”, “drought_index”, “evapo_p”, “evapo_r”, “frost_depth”, “precipitation”, “soil_moist”, “soil_temperature_5cm”, “sunshine_duration”
```
Finally, our package fhpredict has a function to read (and cut) current precipitation data (RADOLAN), see: https://kwb-r.github.io/fhpredict/articles/tutorial.html#spacially-select-and-aggregate-rain-data

**Altogether: Too many different functions that do too many different things...**

**Comment by mrustl** [comment]
Thanks...sh...hot. ;-) 

Will try out .....

**Comment by mrustl** [comment]
Maybe also good if all monthly variables are supported by load_monthly_variable_for_region()`

https://github.com/KWB-R/kwb.dwd/blob/ae99ae10ada664c3dff522f079bab7dfad524f9e/R/load_monthly_variable_for_region.R

**Comment by mrustl** [comment]
solved by https://github.com/KWB-R/kwb.dwd/pull/38
