### ISSUE TITLE
Add argument "as_data_frame" to crop_radolan_radial()

### ISSUE THREAD

**Issue by wseis** [KWB-R/kwb.dwd#6]
Return the data frame only if argument `as_data_frame` is `TRUE` (default). Otherwise return the raster object.

**Comment by hsonne** [comment]
Hi @wseis,
I implemented the feature. Please install the package from the issue_6 branch and test the function:
```
remotes::install_github("kwb-r/kwb.dwd@issue_6")
```
If everything works, you may close this issue.
Regards, Hauke.

**Comment by wseis** [comment]
Hallo Hauke,

bekomme folgende Fehlermeldung nachdem ich issue-6 Version installiert habe

Error in fetch(key) :
  lazy-load database 'C:/Users/wseis/Documents/R/win-library/3.5/kwb.dwd/help/kwb.dwd.rdb' is corrupt

as_data_frame Argument funktioniert nicht.

Gruß,

Wolfgang



Von: Hauke Sonnenberg [mailto:notifications@github.com]
Gesendet: Montag, 20. Mai 2019 15:10
An: KWB-R/kwb.dwd <kwb.dwd@noreply.github.com>
Cc: Wolfgang Seis <Wolfgang.Seis@kompetenz-wasser.de>; Mention <mention@noreply.github.com>
Betreff: Re: [KWB-R/kwb.dwd] Add argument "as_data_frame" to crop_radolan_radial() (#6)


Hi @wseis<https://github.com/wseis>,
I implemented the feature. Please install the package from the issue_6 branch and test the function:

remotes::install_github("kwb-r/kwb.dwd@issue_6")

If everything works, you may close this issue.
Regards, Hauke.

**Comment by hsonne** [comment]
Bei Fehlermeldung „is corrupt“ immer R neustarten (Ctrl+Shift+F10). Das sollte reichen. Ansonsten RStudio neustarten.

Von: wseis [mailto:notifications@github.com]
Gesendet: Montag, 20. Mai 2019 15:34
An: KWB-R/kwb.dwd <kwb.dwd@noreply.github.com>
Cc: Hauke Sonnenberg <Hauke.Sonnenberg@kompetenz-wasser.de>; Assign <assign@noreply.github.com>
Betreff: Re: [KWB-R/kwb.dwd] Add argument "as_data_frame" to crop_radolan_radial() (#6)

Hallo Hauke,

bekomme folgende Fehlermeldung nachdem ich issue-6 Version installiert habe

Error in fetch(key) :
lazy-load database 'C:/Users/wseis/Documents/R/win-library/3.5/kwb.dwd/help/kwb.dwd.rdb' is corrupt

as_data_frame Argument funktioniert nicht.

Gruß,

Wolfgang



Von: Hauke Sonnenberg [mailto:notifications@github.com]
Gesendet: Montag, 20. Mai 2019 15:10
An: KWB-R/kwb.dwd <kwb.dwd@noreply.github.com>
Cc: Wolfgang Seis <Wolfgang.Seis@kompetenz-wasser.de>; Mention <mention@noreply.github.com>
Betreff: Re: [KWB-R/kwb.dwd] Add argument "as_data_frame" to crop_radolan_radial() (#6)


Hi @wseis<https://github.com/wseis>,
I implemented the feature. Please install the package from the issue_6 branch and test the function:

remotes::install_github("kwb-r/kwb.dwd@issue_6")

If everything works, you may close this issue.
Regards, Hauke.
