### ISSUE TITLE
Add "transform_radolan_binary_to_rst()" to kwb-dwd 

### ISSUE THREAD

**Issue by wseis** [KWB-R/kwb.dwd#7]
Please add function to package so that TSB colleagues can see to function

**Comment by hsonne** [comment]
I think that the function has become `convert_bin_to_raster_file()` in the package.
https://github.com/KWB-R/kwb.dwd/blob/c3863e2bb2342ca68fe36d1a3006e3f07d195329/R/convert_bin_to_raster_file.R#L12
